version: 2


phases:

  install:
    runtime-versions:
      docker: 18
    commands:
      - npm install



  prebuild:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - docker build -t omkargujar/react-test -f ./client/Dockerfile.dev ./client
      - docker run -e CI=true omkargujar/react-test npm test
      - docker build -t omkargujar/multi-client ./client
      - docker build -t omkargujar/multi-nginx ./nginx
      - docker build -t omkargujar/multi-server ./server
      - docker build -t omkargujar/multi-worker ./worker

  postbuild:
    commands:
      - docker push omkargujar/multi-client
      - docker push omkargujar/multi-nginx
      - docker push omkargujar/multi-server
      - docker push omkargujar/multi-worker


