version: 0.2


phases:

  install:
    runtime-versions:
      docker: 18
    commands:
      - npm install



  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - docker build -t omkargujar/react-test -f ./client/Dockerfile.dev ./client
      - docker run -e CI=true omkargujar/react-test npm test
      - docker build -t multi-docker/multi-client ./client
      - docker tag multi-docker/multi-client:latest 154729512881.dkr.ecr.ap-south-1.amazonaws.com/multi-docker:latest
      - #docker build -t multi-docker/multi-nginx ./nginx
      - #docker build -t multi-docker/multi-server ./server
      - #docker build -t multi-docker/multi-worker ./worker

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 154729512881.dkr.ecr.ap-south-1.amazonaws.com/multi-docker:latest
      - #docker push omkargujar/multi-client
      - #docker push omkargujar/multi-nginx
      - #docker push omkargujar/multi-server
      - #docker push omkargujar/multi-worker


